server:
  port: 5000


spring:
  application:
    name: GATEWAY-SERVICE





eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/