server:
  port: 5001

spring:
    application:
      name: TASK-USER-SERVICE


    jpa:
     hibernate:
      ddl-auto: update

    datasource:
      url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/user_task_service
      username: root
      password: Biswajit@091
      driver-class-name: com.mysql.cj.jdbc.Driver